nome = input("Digite o nome do cliente: ")
dia_venc = input("Digite o dia de vencimento: ")
mes_venc = input("Digite o mês de vencimento: ")
valor = input("Digite o valor da fatura: ")
print(f"Olá, {nome}\nA sua fatura com vencimento em {dia_venc} de {mes_venc} no valor de R$ {valor} está fechada.") 
